### ISSUE TITLE
Scalar-valued `MarkovKernels.Normal`

### ISSUE THREAD

**Issue by nathanaelbosch** [filtron/MarkovKernels.jl#102]
I tried making a scalar-valued Normal distribution with
```julia
Normal(rand(), rand())
```
but this did not work. Is this a feature that MarkovKernels.jl also wants to support? This would be convenient for me to use.

**Comment by filtron** [comment]
It would be totally fine to add constructor + methods for ```Normal{<:Number,<:Number,<:Number}```
